package basket

import (
	"crypto/rand"
	"crypto/sha256"
	"errors"
	"fmt"
	"strings"
	"time"
)

const (
	basketIDPrefix     = "basket"
	basketItemIDPrefix = "bitem"

	ulidEncodedLength     = 26
	checksumEncodedLength = 8

	crockfordAlphabet = "0123456789ABCDEFGHJKMNPQRSTVWXYZ"
)

var (
	ErrInvalidIDFormat   = errors.New("invalid id format")
	ErrInvalidIDPrefix   = errors.New("invalid id prefix")
	ErrInvalidIDPayload  = errors.New("invalid id payload")
	ErrInvalidIDChecksum = errors.New("invalid id checksum")
)

// NewBasketID returns a stable, opaque, externally safe basket identifier.
//
// Format:
//
//	basket_<26-char-ulid>_<8-char-checksum>
func NewBasketID() (string, error) {
	return newPrefixedID(basketIDPrefix, time.Now)
}

// NewBasketItemID returns a stable, opaque, externally safe basket item
// identifier.
//
// Format:
//
//	bitem_<26-char-ulid>_<8-char-checksum>
func NewBasketItemID() (string, error) {
	return newPrefixedID(basketItemIDPrefix, time.Now)
}

// ValidateBasketID validates a basket identifier generated by NewBasketID.
func ValidateBasketID(id string) error {
	return validatePrefixedID(id, basketIDPrefix)
}

// ValidateBasketItemID validates a basket item identifier generated by
// NewBasketItemID.
func ValidateBasketItemID(id string) error {
	return validatePrefixedID(id, basketItemIDPrefix)
}

func newPrefixedID(prefix string, now func() time.Time) (string, error) {
	payload, err := newULIDPayload(now)
	if err != nil {
		return "", err
	}

	checksum := checksumFor(prefix, payload)

	return fmt.Sprintf("%s_%s_%s", prefix, payload, checksum), nil
}

func validatePrefixedID(id string, expectedPrefix string) error {
	parts := strings.Split(id, "_")
	if len(parts) != 3 {
		return ErrInvalidIDFormat
	}

	prefix := parts[0]
	payload := parts[1]
	checksum := parts[2]

	if prefix != expectedPrefix {
		return ErrInvalidIDPrefix
	}

	if !isValidCrockford(payload, ulidEncodedLength) {
		return ErrInvalidIDPayload
	}

	if !isValidCrockford(checksum, checksumEncodedLength) {
		return ErrInvalidIDChecksum
	}

	expectedChecksum := checksumFor(prefix, payload)
	if checksum != expectedChecksum {
		return ErrInvalidIDChecksum
	}

	return nil
}

func newULIDPayload(now func() time.Time) (string, error) {
	var raw [16]byte

	timestampMillis := uint64(now().UTC().UnixMilli())

	// ULID-style layout:
	// first 48 bits: timestamp in milliseconds
	// next 80 bits: crypto-random entropy
	raw[0] = byte(timestampMillis >> 40)
	raw[1] = byte(timestampMillis >> 32)
	raw[2] = byte(timestampMillis >> 24)
	raw[3] = byte(timestampMillis >> 16)
	raw[4] = byte(timestampMillis >> 8)
	raw[5] = byte(timestampMillis)

	if _, err := rand.Read(raw[6:]); err != nil {
		return "", fmt.Errorf("generate id entropy: %w", err)
	}

	return encodeCrockford128(raw), nil
}

func checksumFor(prefix string, payload string) string {
	sum := sha256.Sum256([]byte(prefix + "_" + payload))

	// First 5 bytes = 40 bits.
	// 40 bits encodes cleanly into 8 Crockford Base32 characters.
	var checksumBytes [5]byte
	copy(checksumBytes[:], sum[:5])

	return encodeCrockford40(checksumBytes)
}

func isValidCrockford(value string, expectedLength int) bool {
	if len(value) != expectedLength {
		return false
	}

	for _, r := range value {
		if !strings.ContainsRune(crockfordAlphabet, r) {
			return false
		}
	}

	return true
}

// encodeCrockford128 encodes 128 bits as 26 Crockford Base32 characters.
//
// ULID strings are 26 characters because 26 * 5 = 130 bits. The top two bits
// are zero for the encoded value.
func encodeCrockford128(value [16]byte) string {
	var out [ulidEncodedLength]byte

	// Treat the 128-bit value as a stream of bits and emit 5-bit groups.
	// There are 130 output bits, so the first group is padded with two zero bits.
	var bitBuffer uint32
	var bitCount uint8
	outIndex := 0

	for _, b := range value {
		bitBuffer = (bitBuffer << 8) | uint32(b)
		bitCount += 8

		for bitCount >= 5 {
			shift := bitCount - 5
			index := (bitBuffer >> shift) & 0x1F
			out[outIndex] = crockfordAlphabet[index]
			outIndex++

			bitBuffer &= (1 << shift) - 1
			bitCount -= 5
		}
	}

	if bitCount > 0 {
		index := (bitBuffer << (5 - bitCount)) & 0x1F
		out[outIndex] = crockfordAlphabet[index]
	}

	return string(out[:])
}

// encodeCrockford40 encodes exactly 40 bits as 8 Crockford Base32 characters.
func encodeCrockford40(value [5]byte) string {
	var out [checksumEncodedLength]byte

	out[0] = crockfordAlphabet[(value[0]>>3)&0x1F]
	out[1] = crockfordAlphabet[((value[0]&0x07)<<2)|(value[1]>>6)]
	out[2] = crockfordAlphabet[(value[1]>>1)&0x1F]
	out[3] = crockfordAlphabet[((value[1]&0x01)<<4)|(value[2]>>4)]
	out[4] = crockfordAlphabet[((value[2]&0x0F)<<1)|(value[3]>>7)]
	out[5] = crockfordAlphabet[(value[3]>>2)&0x1F]
	out[6] = crockfordAlphabet[((value[3]&0x03)<<3)|(value[4]>>5)]
	out[7] = crockfordAlphabet[value[4]&0x1F]

	return string(out[:])
}
